import os
from collections import defaultdict
from decimal import Decimal

from django.conf import settings

from crm.models import Deals


def safe_filename(name):
    return "".join(c for c in (name or "") if c.isalnum() or c in (" ", "_", "-")).strip().replace(" ", "_")


def get_supplier_reports_base_dir():
    base_dir = os.path.join(settings.MEDIA_ROOT, "supplier_shipment_reports")
    os.makedirs(base_dir, exist_ok=True)
    return base_dir


def get_supplier_reports_month_dir(year, month):
    month_str = str(month).zfill(2)
    month_dir = os.path.join(get_supplier_reports_base_dir(), str(year), month_str)
    os.makedirs(month_dir, exist_ok=True)
    return month_dir


def clear_supplier_reports_month_dir(year, month):
    month_dir = get_supplier_reports_month_dir(year, month)

    for file_name in os.listdir(month_dir):
        if file_name.lower().endswith(".pdf"):
            file_path = os.path.join(month_dir, file_name)
            if os.path.isfile(file_path):
                os.remove(file_path)


def get_month_supplier_deals(year, month):
    return (
        Deals.objects
        .filter(date__year=year, date__month=month)
        .exclude(supplier__isnull=True)
        .select_related("supplier", "buyer", "transport_company")
        .order_by("supplier__name", "date")
    )


def group_deals_by_supplier(deals):
    grouped = defaultdict(list)

    for deal in deals:
        if deal.supplier:
            grouped[deal.supplier].append(deal)

    return grouped


def generate_single_supplier_shipment_report_pdf(supplier, deals, output_path, year, month):
    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen import canvas
    from reportlab.platypus import Table, TableStyle
    from reportlab.lib import colors
    from reportlab.lib.utils import ImageReader

    pdf = canvas.Canvas(output_path, pagesize=A4)
    PAGE_W, PAGE_H = A4

    M_L, M_R, M_T, M_B = 30, 30, 40, 40
    usable_w = PAGE_W - M_L - M_R

    logo_path = os.path.join(settings.BASE_DIR, 'crm', 'static', 'crm', 'images', 'log.png')
    first_deal = deals[0] if deals else None

    # ===== Цвета/хелперы для футера =====
    TEXT_MUTED = colors.HexColor("#555555")  # приглушённый текст

    def hr(y):
        """Горизонтальная тонкая линия-разделитель"""
        pdf.setStrokeColor(colors.HexColor("#aaaaaa"))
        pdf.setLineWidth(0.5)
        pdf.line(M_L, y, PAGE_W - M_R, y)

    data = [["Date", "Grade", "Net (MT)", "Price ($/MT)", "Amount ($)"]]

    for d in deals:
        data.append([
            d.date.strftime("%Y-%m-%d"),
            str(d.grade),
            f"{float(d.received_quantity or 0):.3f}",
            f"{float(d.supplier_price or 0):.2f}",
            f"{float(d.supplier_total or 0):.2f}",
        ])

    total_net = sum(float(d.received_quantity or 0) for d in deals)
    total_amount = sum(float(d.supplier_total or 0) for d in deals)

    def draw_header():
        y = PAGE_H - 60

        if os.path.exists(logo_path):
            pdf.drawImage(ImageReader(logo_path), M_L, y - 50, width=70, height=70, mask='auto')

        pdf.setFont("Helvetica-Bold", 16)
        pdf.drawCentredString(PAGE_W / 2, y, "Shipment Summary")

        pdf.setFont("Helvetica-Bold", 11)
        pdf.setFillColor(colors.darkblue)
        pdf.drawRightString(PAGE_W - M_R, y, "Local to Global Recycling Inc.")

        pdf.setFont("Helvetica", 9)
        pdf.setFillColor(colors.HexColor("#555555"))
        pdf.drawRightString(PAGE_W - M_R, y - 14, "19090 Lougheed Hwy.")
        pdf.drawRightString(PAGE_W - M_R, y - 26, "Pitt Meadows, BC V3Y 2M6")
        pdf.drawRightString(PAGE_W - M_R, y - 38, "wastepaperbrokers.com")

        pdf.setStrokeColor(colors.HexColor("#aaaaaa"))
        pdf.setLineWidth(0.5)
        pdf.line(M_L, y - 50, PAGE_W - M_R, y - 50)

        lines = []
        if first_deal and first_deal.supplier:
            lines.append(first_deal.supplier.name)
            contact = first_deal.supplier.contacts.filter(address__isnull=False).first()
            if contact and contact.address:
                lines.extend([ln.strip() for ln in contact.address.strip().split('\n') if ln.strip()])
            else:
                lines.append("Address not available")
        else:
            lines.append("Unknown")

        pdf.setFont("Helvetica", 10)
        y_lines = PAGE_H - 135
        for ln in lines:
            pdf.drawString(M_L + 55, y_lines, ln)
            y_lines -= 14

        return y_lines - 12

    def draw_footer():
        # Нижняя линия + подпись всегда на одинаковой высоте
        hr(M_B + 18)
        pdf.setFont("Helvetica", 8);
        pdf.setFillColor(TEXT_MUTED)
        pdf.drawString(M_L, M_B + 6, "Thank you for recycling responsibly.")
        pdf.drawRightString(PAGE_W - M_R, M_B + 6, "Generated by ADAM CRM")

    def table_style():
        return TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
        ])

    def ensure_space_or_new_page(y_cur, need=40):
        if y_cur - need < M_B + 30:
            draw_footer()
            pdf.showPage()
            return draw_header()
        return y_cur

    def draw_table_paginated(all_rows, start_y):
        col_widths = [80, 160, 80, 90, 100]
        header = all_rows[0]
        rows = all_rows[1:]

        i, y_cur = 0, start_y

        while i < len(rows):
            low, high, fit = 1, len(rows) - i, 0
            while low <= high:
                mid = (low + high) // 2
                trial = [header] + rows[i:i + mid]
                t_try = Table(trial, colWidths=col_widths)
                t_try.setStyle(table_style())
                w_try, h_try = t_try.wrap(usable_w, 0)
                if y_cur - h_try >= M_B:
                    fit = mid
                    low = mid + 1
                else:
                    high = mid - 1

            if fit == 0:
                draw_footer()
                pdf.showPage()
                y_cur = draw_header()
                continue

            chunk = [header] + rows[i:i + fit]
            t = Table(chunk, colWidths=col_widths)
            t.setStyle(table_style())
            w, h = t.wrap(usable_w, 0)
            x = M_L + (usable_w - w) / 2
            t.drawOn(pdf, x, y_cur - h)
            y_cur -= h + 10
            i += fit

            if i < len(rows) and y_cur < M_B + 60:
                draw_footer()
                pdf.showPage()
                y_cur = draw_header()

        return y_cur

    y = draw_header()
    y = draw_table_paginated(data, y - 10)

    y -= 40
    y = ensure_space_or_new_page(y, need=40)
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(M_L, y, f"Net Weight: {total_net:.2f} MT")
    y -= 18
    pdf.drawString(M_L, y, f"Amount Due: ${total_amount:.2f}")
    y -= 24

    grade_summary = {}
    for d in deals:
        key = (str(d.grade), float(d.supplier_price or 0))
        if key not in grade_summary:
            grade_summary[key] = {"net": 0.0, "amount": 0.0}
        grade_summary[key]["net"] += float(d.received_quantity or 0)
        grade_summary[key]["amount"] += float(d.supplier_total or 0)

    items = sorted(grade_summary.items(), key=lambda kv: (kv[0][0], kv[0][1]))
    pdf.setFont("Helvetica", 10)
    for (grade, price), vals in items:
        line = f"{grade} (${price:.2f}) - {vals['net']:.2f} MT - ${vals['amount']:.2f}"
        y = ensure_space_or_new_page(y, need=16)
        pdf.drawString(M_L, y, line)
        y -= 14

    draw_footer()
    pdf.save()


def generate_supplier_shipment_reports_for_month(year, month):
    clear_supplier_reports_month_dir(year, month)

    deals = get_month_supplier_deals(year, month)
    grouped = group_deals_by_supplier(deals)
    month_dir = get_supplier_reports_month_dir(year, month)

    generated_files = []

    for supplier, supplier_deals in grouped.items():
        file_name = f"{safe_filename(supplier.name)}.pdf"
        output_path = os.path.join(month_dir, file_name)

        generate_single_supplier_shipment_report_pdf(
            supplier=supplier,
            deals=supplier_deals,
            output_path=output_path,
            year=year,
            month=month,
        )

        generated_files.append(output_path)

    return generated_files