# Generated by Django 5.1.5 on 2025-10-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
