# Generated by Django 5.1.5 on 2025-10-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0002_scaleday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScaleDay',
        ),
        migrations.AddField(
            model_name='receivedmaterial',
            name='report_day',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
