# Generated by Django 5.1.5 on 2025-11-21 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0003_delete_scaleday_receivedmaterial_report_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivedmaterial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Received Material', 'verbose_name_plural': 'Received Materials'},
        ),
        migrations.AlterField(
            model_name='receivedmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='receivedmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receivedmaterial',
            name='gross_kg',
            field=models.DecimalField(decimal_places=2, help_text='Gross weight in kilograms', max_digits=10),
        ),
        migrations.AlterField(
            model_name='receivedmaterial',
            name='material',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='receivedmaterial',
            name='net_kg',
            field=models.DecimalField(decimal_places=2, help_text='Net weight in kilograms', max_digits=10),
        ),
        migrations.AlterField(
            model_name='receivedmaterial',
            name='supplier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receivedmaterial',
            name='tag',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='receivedmaterial',
            index=models.Index(fields=['-created_at'], name='scales_rece_created_be1b20_idx'),
        ),
        migrations.AddIndex(
            model_name='receivedmaterial',
            index=models.Index(fields=['report_day', 'company_slug'], name='scales_rece_report__4a8855_idx'),
        ),
        migrations.AddIndex(
            model_name='receivedmaterial',
            index=models.Index(fields=['company_slug', '-created_at'], name='scales_rece_company_398d01_idx'),
        ),
    ]
