# Generated by Django 5.1.3 on 2024-12-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_amount_deals_buyer_price_remove_deals_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('suppliers', 'Suppliers'), ('buyers', 'Buyers')], default='suppliers', max_length=10),
        ),
    ]
