# Generated by Django 5.1.3 on 2024-12-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_client_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='type',
            new_name='client_type',
        ),
    ]
