# Generated by Django 5.1.5 on 2025-02-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_pipeline_client_remove_pipeline_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
