# Generated by Django 5.1.3 on 2024-12-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_deals_buyer_alter_deals_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='buyer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='supplier',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
