# Generated by Django 5.1.3 on 2024-12-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_deals_buyer_alter_deals_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('suppliers', 'Suppliers'), ('hauler', 'Hauler'), ('buyers', 'Buyers')], default='suppliers', max_length=10),
        ),
    ]
