# Generated by Django 5.1.3 on 2024-12-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_client_client_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('pallets_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='deals',
            name='pallets_delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deals',
            name='pallets_received',
            field=models.IntegerField(default=0),
        ),
    ]
