# Generated by Django 5.1.3 on 2024-12-27 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_clientpallets_deals_pallets_delivered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallets_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientPallets',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='pallets_delivered',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='pallets_received',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_clients', to='crm.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('hauler', 'Hauler'), ('buyer', 'Buyer')], default='suppliers', max_length=10),
        ),
        migrations.AddField(
            model_name='companypallets',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='crm.client'),
        ),
    ]
