# Generated by Django 5.1.3 on 2024-12-27 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_companypallets_delete_clientpallets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('suppliers', 'Suppliers'), ('hauler', 'Hauler'), ('buyers', 'Buyers')], default='suppliers', max_length=10),
        ),
        migrations.AlterField(
            model_name='companypallets',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='crm.deals'),
        ),
    ]
