# Generated by Django 5.1.5 on 2025-03-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_scheduledshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypallets',
            name='cages_count',
            field=models.IntegerField(default=0),
        ),
    ]
