# Generated by Django 5.1.5 on 2025-04-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_deals_transport_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pickup_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactmaterial',
            name='material',
            field=models.CharField(choices=[('OCC 11', 'OCC 11'), ('OCC 11 Bale String', 'OCC 11 Bale String'), ('Flexible Plastic', 'Flexible Plastic'), ('Mixed Container', 'Mixed Container'), ('Pallets', 'Pallets'), ('Kraft Paper Bags', 'Kraft Paper Bags'), ('Loose OCC', 'Loose OCC'), ('Printers Offcuts', 'Printers Offcuts'), ('Brown Printers Offcuts', 'Brown Printers Offcuts'), ('Stock Rolls', 'Stock Rolls'), ('Baled Cardboard', 'Baled Cardboard')], max_length=255),
        ),
        migrations.AlterField(
            model_name='deals',
            name='grade',
            field=models.CharField(choices=[('OCC 11', 'OCC 11'), ('OCC 11 Bale String', 'OCC 11 Bale String'), ('Flexible Plastic', 'Flexible Plastic'), ('Mixed Container', 'Mixed Container'), ('Pallets', 'Pallets'), ('Kraft Paper Bags', 'Kraft Paper Bags'), ('Loose OCC', 'Loose OCC'), ('Printers Offcuts', 'Printers Offcuts'), ('Brown Printers Offcuts', 'Brown Printers Offcuts'), ('Stock Rolls', 'Stock Rolls'), ('Baled Cardboard', 'Baled Cardboard')], max_length=255),
        ),
    ]
