# Generated by Django 5.1.3 on 2024-12-27 21:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_type', models.CharField(choices=[('suppliers', 'Suppliers'), ('hauler', 'Hauler'), ('buyers', 'Buyers')], default='suppliers', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.CharField(default=0, max_length=255)),
                ('buyer', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(default='A', max_length=50)),
                ('shipped_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipped_pallets', models.PositiveIntegerField(default=0)),
                ('scale_ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received_pallets', models.IntegerField(default=0)),
                ('supplier_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier_currency', models.CharField(default='CAD', max_length=10)),
                ('supplier_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buyer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer_currency', models.CharField(default='CAD', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_company', models.CharField(blank=True, max_length=255, null=True)),
                ('total_income_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallets_count', models.IntegerField(default=0)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='PipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sellers')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('stage', models.CharField(max_length=100, verbose_name='Stage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_clients', to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
            ],
        ),
    ]
