# Generated by Django 5.1.3 on 2025-01-03 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_deals_buyer_alter_deals_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='companypallets',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='crm.company'),
        ),
    ]
