# Generated by Django 5.1.3 on 2025-01-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_contact_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='received_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='shipped_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
