# Generated by Django 5.1.3 on 2025-01-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_deals_received_quantity_and_more'),
        ('crm', '0005_material_alter_deals_received_quantity_and_more'),
    ]

    operations = [
    ]
