# Generated by Django 5.1.3 on 2025-02-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_merge_20250115_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='current_price',
        ),
        migrations.AlterField(
            model_name='contactmaterial',
            name='material',
            field=models.CharField(choices=[('OCC 11', 'OCC 11'), ('OCC 11 Bale String', 'OCC 11 Bale String'), ('Flexible Plastic', 'Flexible Plastic'), ('Mixed Container', 'Mixed Container'), ('Pallets', 'Pallets'), ('Kraft Paper Bags', 'Kraft Paper Bags'), ('Loose OCC', 'Loose OCC')], max_length=255),
        ),
        migrations.AlterField(
            model_name='deals',
            name='grade',
            field=models.CharField(choices=[('OCC 11', 'OCC 11'), ('OCC 11 Bale String', 'OCC 11 Bale String'), ('Flexible Plastic', 'Flexible Plastic'), ('Mixed Container', 'Mixed Container'), ('Pallets', 'Pallets'), ('Kraft Paper Bags', 'Kraft Paper Bags'), ('Loose OCC', 'Loose OCC')], max_length=255),
        ),
    ]
