# Generated by Django 5.1.5 on 2025-02-18 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_contact_current_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='client',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('send_email', 'Send Email'), ('meeting', 'Meeting'), ('account', 'Account'), ('deal', 'Deal')], default='new', max_length=20),
        ),
    ]
