# Generated by Django 5.1.5 on 2025-02-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_deals_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='licence_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
