# Generated by Django 5.1.5 on 2025-02-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_deals_licence_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='gross_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='net_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='tare_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
