# Generated by Django 5.1.5 on 2025-03-18 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_event_remove_deals_gross_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('grade', models.CharField(max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_receipts', to='crm.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_shipments', to='crm.company')),
            ],
        ),
    ]
