# Generated by Django 5.1.5 on 2025-03-21 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_companypallets_cages_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='company',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.contact'),
        ),
    ]
