# Generated by Django 5.1.5 on 2025-03-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_remove_pipeline_company_pipeline_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
