# Generated by Django 5.1.5 on 2025-03-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_pipeline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='transport_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_hauler', to='crm.company'),
        ),
    ]
