# Generated by Django 5.1.5 on 2025-05-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_scheduledshipment_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypallets',
            name='bags_count',
            field=models.IntegerField(default=0),
        ),
    ]
