# Generated by Django 5.1.5 on 2025-06-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_remove_task_client_task_company_task_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCaleTicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255, unique=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
