# Generated by Django 5.1.5 on 2025-07-03 00:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_remove_scheduledshipment_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledshipment',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_receipts', to='crm.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledshipment',
            name='date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledshipment',
            name='grade',
            field=models.CharField(default='OCC', max_length=100),  # Заменено значение по умолчанию
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledshipment',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledshipment',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_shipments', to='crm.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledshipment',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),  # ✅ исправлено здесь
            preserve_default=False,
        ),

    ]
