# Generated by Django 5.1.5 on 2025-07-11 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_scheduledshipment_buyer_scheduledshipment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=50)),
                ('max_bales', models.IntegerField()),
                ('max_tons', models.FloatField()),
                ('base_cost', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
            ],
        ),
    ]
