# Generated by Django 5.1.5 on 2025-07-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_truckprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckprofile',
            name='bale_weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
