# Generated by Django 5.1.5 on 2025-07-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_truckprofile_bale_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckprofile',
            name='truck_name',
        ),
        migrations.AddField(
            model_name='truckprofile',
            name='max_spots',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
