# Generated by Django 5.1.5 on 2025-07-15 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_remove_truckprofile_truck_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckprofile',
            name='bale_weight',
        ),
    ]
