# Generated by Django 5.1.5 on 2025-11-12 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_alter_contactmaterial_material_alter_deals_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipientPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_recipient_prefs', to='crm.company')),
                ('contacts', models.ManyToManyField(blank=True, related_name='email_recipient_prefs', to='crm.contact')),
            ],
            options={
                'unique_together': {('company', 'context')},
            },
        ),
    ]
