# Generated by Django 5.1.5 on 2025-11-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_emailrecipientpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailrecipientpreference',
            name='contacts',
        ),
        migrations.AddField(
            model_name='emailrecipientpreference',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='email_recipient_prefs', to='crm.employee'),
        ),
    ]
