# Generated by Django 5.1.5 on 2025-12-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_companyemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='scale_ticket_sent',
            field=models.BooleanField(default=False),
        ),
    ]
