# Generated by Django 5.1.5 on 2025-10-17 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Отображаемое имя компании на стартовой странице.', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Ключ компании для маршрутизации (пример: local-to-global).', max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Логотип компании.', null=True, upload_to='entry_portal_logos/')),
                ('redirect_url', models.CharField(blank=True, help_text='Куда перенаправлять после выбора компании (пример: /crm/dashboard).', max_length=255, validators=[django.core.validators.URLValidator(message='Можно задать и абсолютный URL.', schemes=['http', 'https'])])),
                ('is_active', models.BooleanField(default=True, help_text='Если выключено — компания не показывается на экране выбора.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения на экране выбора (меньше число — выше).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компания портала',
                'verbose_name_plural': 'Компании портала',
                'ordering': ['order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='entryportal_slug_not_empty')],
            },
        ),
    ]
