# Generated by Django 5.1.5 on 2025-10-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcompany',
            name='shared_password',
            field=models.CharField(blank=True, help_text='Хэш общего пароля компании (задаётся через админку/скрипт).', max_length=255),
        ),
        migrations.AlterField(
            model_name='portalcompany',
            name='redirect_url',
            field=models.CharField(blank=True, help_text='Куда перенаправлять после выбора (пример: /crm/dashboard или /scales/home).', max_length=255),
        ),
    ]
