# Generated by Django 5.1.5 on 2025-10-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_portal', '0002_portalcompany_shared_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portalcompany',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='portalcompany',
            name='entryportal_slug_not_empty',
        ),
        migrations.RemoveField(
            model_name='portalcompany',
            name='shared_password',
        ),
        migrations.AddField(
            model_name='portalcompany',
            name='manager_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='portalcompany',
            name='staff_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portalcompany',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='portalcompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='entry_portal_logos/'),
        ),
        migrations.AlterField(
            model_name='portalcompany',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='portalcompany',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portalcompany',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portalcompany',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
